#!/usr/bin/env sh

swaynag -t error -m 'Power options' \
	-Z 'Suspend' 'sleep 3; systemctl hybrid-sleep' \
	-Z 'Hibernate' 'sleep 3; systemctl suspend-then-hibernate' \
	-Z 'Exit Sway' 'swaymsg exit' \
	-Z 'Reload Sway' 'swaymsg reload' \
	-Z 'Lock' 'loginctl lock-session' \
	-s 'Cancel'
