# v5.0.0-rc.1
### Configuration
[buildPlans.iosevka-mithic]
family = "Iosevka Mithic"
spacing = "term"
serifs = "sans"

  [buildPlans.iosevka-mithic.variants]
  inherits = "ss05"

    [buildPlans.iosevka-mithic.variants.design]
    capital-g = "toothed-serifless-hooked"
    capital-k = "straight"
    f = "flat-hook-crossbar-at-x-height"
    g = "double-storey"
    k = "straight"
    t = "flat-hook"
    eszet = "sulzbacher"
    capital-gamma = "motion-serifed"
    lower-iota = "flat-tailed"
    lower-lambda = "straight"
    one = "base"
    two = "curly-neck"
    four = "closed"
    nine = "open-contour"
    underscore = "high"
    paragraph-sign = "high"
    caret = "low"
    brace = "straight"
    number-sign = "upright"
    ampersand = "closed"
    at = "threefold"
    dollar = "open"
    lig-ltgteq = "flat"

    [buildPlans.iosevka-mithic.variants.italic]
    a = "single-storey-earless-corner-tailed"
    b = "toothless-corner"
    d = "toothless-corner"
    g = "earless-corner"
    i = "serifed-flat-tailed"
    k = "cursive"
    l = "serifed-flat-tailed"
    p = "earless-corner"
    q = "earless-corner"
    r = "serifless"
    u = "toothless-corner"
    y = "cursive"
    zero = "dotted"
    one = "nobase"
    six = "straight-bar"
    nine = "straight-bar"
    underscore = "above-baseline"
    ampersand = "upper-open"
    percent = "dots"
    bar = "force-upright"

  [buildPlans.iosevka-mithic.ligations]
  inherits = "dlig"

[buildPlans.iosevka-mithic.weights.thin]
shape = 100
menu = 100
css = 100

[buildPlans.iosevka-mithic.weights.extralight]
shape = 200
menu = 200
css = 200

[buildPlans.iosevka-mithic.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-mithic.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-mithic.weights.book]
shape = 450
menu = 450
css = 450

[buildPlans.iosevka-mithic.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-mithic.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-mithic.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-mithic.weights.extrabold]
shape = 800
menu = 800
css = 800

[buildPlans.iosevka-mithic.weights.heavy]
shape = 900
menu = 900
css = 900

[buildPlans.iosevka-mithic.widths.normal]
shape = 576
menu = 5
css = "normal"


### Building font
# - Everything (TTF + Web Font):
#   npm run build -- contents::iosevka-mithic
# - TTF (hinted):
#   npm run build -- ttf::iosevka-mithic
# - Unhinted TTF:
#   npm run build -- ttf-unhinted::iosevka-mithic
