brace_style = "AlwaysNextLine"
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"  # def
disable_all_formatting = false  # def
empty_item_single_line = true  # def
enum_discrim_align_threshold = 80
fn_args_layout = "Tall"  # def
force_multiline_blocks = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
format_macro_matchers = true
format_macro_bodies = true
format_strings = false  # def
hard_tabs = true
hex_literal_case = "Lower"
imports_layout = "HorizontalVertical"
indent_style = "Block"  # def
inline_attribute_width = 0  # def
match_arm_blocks = false
match_arm_leading_pipes = "Never"  # def
match_block_trailing_comma = true
max_width = 80
merge_derives = true  # def
newline_style = "Unix"
normalize_comments = false
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true  # def
group_imports = "StdExternalCrate"
reorder_modules = true  # def
short_array_element_width_threshold = 0
struct_field_align_threshold = 80
struct_lit_width = 0
struct_variant_width = 0
tab_spaces = 8
unstable_features = false
use_small_heuristics = "Off"
use_try_shorthand = true
wrap_comments = true
