complete -c procs -n "__fish_use_subcommand" -s W -l watch-interval -d 'Watch mode with custom interval'
complete -c procs -n "__fish_use_subcommand" -s i -l insert -d 'Insert column to slot'
complete -c procs -n "__fish_use_subcommand" -l only -d 'Specified column only'
complete -c procs -n "__fish_use_subcommand" -l sorta -d 'Sort column by ascending'
complete -c procs -n "__fish_use_subcommand" -l sortd -d 'Sort column by descending'
complete -c procs -n "__fish_use_subcommand" -s c -l color -d 'Color mode' -r -f -a "auto always disable"
complete -c procs -n "__fish_use_subcommand" -s p -l pager -d 'Pager mode' -r -f -a "auto always disable"
complete -c procs -n "__fish_use_subcommand" -l interval -d 'Interval to calculate throughput'
complete -c procs -n "__fish_use_subcommand" -l completion -d 'Generate shell completion file' -r -f -a "zsh bash fish powershell elvish"
complete -c procs -n "__fish_use_subcommand" -s a -l and -d 'AND  logic for multi-keyword'
complete -c procs -n "__fish_use_subcommand" -s o -l or -d 'OR   logic for multi-keyword'
complete -c procs -n "__fish_use_subcommand" -s d -l nand -d 'NAND logic for multi-keyword'
complete -c procs -n "__fish_use_subcommand" -s r -l nor -d 'NOR  logic for multi-keyword'
complete -c procs -n "__fish_use_subcommand" -s l -l list -d 'Show list of kind'
complete -c procs -n "__fish_use_subcommand" -s t -l tree -d 'Tree view'
complete -c procs -n "__fish_use_subcommand" -s w -l watch -d 'Watch mode with default interval (1s)'
complete -c procs -n "__fish_use_subcommand" -l config -d 'Generate configuration sample file'
complete -c procs -n "__fish_use_subcommand" -l no-header -d 'Suppress header'
complete -c procs -n "__fish_use_subcommand" -l debug -d 'Show debug message'
complete -c procs -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c procs -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
