local fb_actions = require('telescope._extensions.file_browser.actions')
local extra = require('plugins.telescope.extra')

return {
	cwd_to_path = false,
	grouped = false,
	files = true,
	add_dirs = true,
	depth = 1,
	auto_depth = false,
	select_buffer = true,
	hidden = true,
	respect_gitignore = false,
	hide_parent_dir = false,
	collapse_dirs = false,
	quiet = false,
	dir_icon = 'D',
	dir_icon_hl = 'Default',
	display_stat = { date = true, size = true, mode = true },
	hijack_netrw = false,
	use_fd = true,
	git_status = true,
	prompt_path = true,
	mappings = {
		['i'] = {
			['<S-Cr>'] = fb_actions.create_from_prompt,
			['<C-Cr>'] = fb_actions.change_cwd,
			['<A-Cr>'] = extra.fb_rifle,
			['<C-h>']  = fb_actions.toggle_hidden,
			['<C-w>']  = fb_actions.goto_cwd,
			['<Bs>']   = fb_actions.backspace,
			['<A-c>'] = false,
			['<A-r>'] = false,
			['<A-m>'] = false,
			['<A-y>'] = false,
			['<A-d>'] = false,
			['<C-o>'] = false,
			['<C-g>'] = false,
			['<C-e>'] = false,
			['<C-f>'] = false,
			['<C-s>'] = false,
		},
		['n'] = {
			['<localleader>o'] = fb_actions.create,
			['<localleader>r'] = fb_actions.rename,
			['<localleader>R'] = fb_actions.move,
			['<localleader>y'] = fb_actions.copy,
			['<localleader>x'] = require('plugins.telescope.file_browser_trash'),
			['<localleader>d'] = extra.fb_dragon_drop,
			['<S-Cr>'] = fb_actions.create_from_prompt,
			['<C-Cr>'] = fb_actions.change_cwd,
			['<A-Cr>'] = extra.fb_rifle,
			['<C-h>']  = fb_actions.toggle_hidden,
			['<C-w>']  = fb_actions.goto_cwd,
			['<Bs>']   = fb_actions.backspace,
			['u'] = fb_actions.goto_parent_dir,
			['~'] = fb_actions.goto_home_dir,
		},
	},
}
