local modemap = {
	['n']     = 'NORMAL',
	['no']    = 'PENDNG',
	['nov']   = 'PENDNG',
	['noV']   = 'PENDNG',
	['no\22'] = 'PENDNG',
	['niI']   = 'NORMAL',
	['niR']   = 'NORMAL',
	['niV']   = 'NORMAL',
	['nt']    = 'NORMAL',
	['ntT']   = 'NORMAL',
	['v']     = 'VISUAL',
	['vs']    = 'VISUAL',
	['V']     = 'V-LINE',
	['Vs']    = 'V-LINE',
	['\22']   = 'V-BLCK',
	['\22s']  = 'V-BLCK',
	['s']     = 'SELECT',
	['S']     = 'S-LINE',
	['\19']   = 'S-BLCK',
	['i']     = 'INSERT',
	['ic']    = 'INSERT',
	['ix']    = 'INSERT',
	['R']     = 'REPLCE',
	['Rc']    = 'REPLCE',
	['Rx']    = 'REPLCE',
	['Rv']    = 'V-RPLC',
	['Rvc']   = 'V-RPLC',
	['Rvx']   = 'V-RPLC',
	['c']     = 'COMMND',
	['cv']    = 'EX-CMD',
	['ce']    = 'EX-CMD',
	['r']     = 'REPLCE',
	['rm']    = 'MORE  ',
	['r?']    = 'CONFRM',
	['!']     = 'SHELL ',
	['t']     = 'TERMNL',
}
return function()
	local mode_code = vim.api.nvim_get_mode().mode
	return modemap[mode_code] or mode_code
end
