[greenclip]
blacklisted_applications = []
enable_image_support = true
history_file = "/home/mithic/.cache/greenclip.history"
image_cache_directory = "/tmp/greenclip"
max_history_length = 15
max_selection_size_bytes = 262144
static_history = [
    "————————",
    "‎LTR",
]
trim_space_from_selection = false
use_primary_selection_as_input = false
