format = """
$status$cmd_duration$directory\
$username$hostname\
$singularity\
$kubernetes\
$docker_context\
$terraform\
$nix_shell\
$aws\
$gcloud\
$openstack\
[❯](bold blue)[❯](bold cyan)[❯](bold green) ${custom.cursor}"""

right_format = """
$python\
$git_state$git_status$git_branch$hg_branch\
$jobs$shlvl$memory_usage$battery$time \
"""

add_newline = false
scan_timeout=25
command_timeout=200


[character]
success_symbol = '[✔](green)'
error_symbol = '[✖](red)'
disabled = false

[status]
format = '[↦](bold) [$status( \($signal_name\))]($style) [|](bold)'
style = 'bold red'
recognize_signal_code = true
map_symbol = true
disabled = false

[cmd_duration]
min_time = 2_500
format = ' [$duration]($style) [|](bold)'
style = 'bold yellow'
show_notifications = true
min_time_to_notify = 90_000
disabled = false

[directory]
format = ' [$path]($style)[$read_only]($read_only_style) '
style = 'blue'
read_only = ' ✕'
read_only_style = 'bold red'
truncation_length = 6
truncate_to_repo = false
truncation_symbol = '…/'
disabled = false

[username]
format = '[|](bold) [$user]($style) '
style_root = 'bold red'
style_user = 'bold bright-green'
show_always = false
disabled = false

[hostname]
format = 'at [$hostname]($style) '
trim_at = ''
style = 'bold green'
disabled = false


[python]
format = '([$virtualenv]($style) [|](bold) )'
style = 'bold bright-yellow'
disabled = false

[git_commit]
format = '\([$hash(-$tag)]($style)\) '
tag_symbol = ''
style = 'green'
only_detached = false
tag_disabled = false
disabled = false

[git_state]
format = 'while [$state]($style) (\([$progress_current/$progress_total]($style)\))'
rebase = 'RBS'
merge = 'MRG'
revert = 'RVR'
cherry_pick = 'CHR'
bisect = 'BSC'
am = 'AML'
am_or_rebase = 'A/R'
style = 'bold red'
disabled = false

[git_status]
format = '(\[[$all_status$ahead_behind]($style)\] )'
conflicted = '='
ahead = '↑'
behind = '↓'
diverged = '⇕'
untracked = '?'
stashed = '\$'
modified = '!'
staged = '+'
renamed = '»'
deleted = '-'
style = 'bold cyan'
disabled = false

[git_branch]
format = '[$symbol$branch]($style)( [$remote_branch]($style)) [|](bold) '
symbol = ' '
style = 'bold purple'
truncation_length="10"
only_attached = false
disabled = false

[hg_branch]
format = '[$symbol$branch]($style) [|](bold) '
symbol = ' '
style = 'bold bright-purple'
truncation_length="10"
disabled = false

[shlvl]
threshold = 2
format = '[$symbol$shlvl]($style) [|](bold) '
symbol = '↕'
disabled = false

[jobs]
format = '[$symbol$number]($style) [|](bold) '
symbol = '+'
style = 'bold bright-blue'
symbol_threshold = 1
number_threshold = 1
disabled = false

[memory_usage]
format = '[$ram]($style) [|](bold) '
style = 'bold red'
threshold = 80
disabled = false

[battery]
format = '[$symbol$percentage]($style) [|](bold)'
style = 'yellow'
disabled = false
[[battery.display]]
threshold = 20
style = 'bold yellow'

[time]
format = '[$time]($style)'
style = 'bright-yellow'
disabled = false


[shell]
format = '[$indicator](bold underline cyan)'
fish_indicator = "fish"
zsh_indicator = "zsh"
bash_indicator = "bash"
powershell_indicator = "powershell"
ion_indicator  = "ion"
elvish_indicator = "elvish"
tcsh_indicator = "tcsh"
disabled = false

[nodejs]
format = ', [$symbol$version]($style)'
symbol = 'node '
style = 'green'
not_capable_style = 'bold red'
disabled = false

[rust]
format = ', [$symbol$version]($style)'
symbol = 'rust '
style = 'red'
disabled = false

[lua]
format = ', [$symbol$version]($style)'
symbol = "lua "
style = "blue"
disabled = false

[java]
format = ', [$symbol$version]($style)'
symbol = "java "
style = "bright-red"
disabled = false

[cmake]
format = ', [$symbol$version]($style)'
symbol = "cmake "
style = "bright-blue"
disabled = false

[perl]
format = ', [$symbol$version]($style)'
symbol = "perl "
style = "bright-yellow"
disabled = false


[custom.cursor]
command = "printf '\\e[5 q'"
description = 'Sets terminal cursor to line'
style = 'none'
format = '$output'
when = 'true'
symbol = ''
disabled = false
