daemonize = false
max_history = 100
history_file_path = '/home/mithic/.cache/clipcat/clipcatd/db'
log_level = 'TRACE'

[monitor]
load_current = true
enable_clipboard = true
enable_primary = false

[grpc]
host = '127.0.0.1'
port = 45045
